### ISSUE TITLE
Confusion about nested YAML field naming

### ISSUE THREAD

**Issue by jh125486** [alecthomas/kong-yaml#12]
I've got an example here: https://goplay.tools/snippet/BgLnHxAlWLx

Basically, given equivalent JSON and YAML, the YAML resolver isn't picking up the same nested struct names as the JSON resolver.  I know I'm doing something wrong, I just can't figure it out.
```go
package main

import (
	"fmt"
	"strings"

	"github.com/alecthomas/kong"
	kongyaml "github.com/alecthomas/kong-yaml"
)

type (
	CLI struct {
		AValue1 Value `prefix:"aValue1." embed:"" name:"aValue1"`
		AValue2 Value `prefix:"aValue2." embed:"" name:"aValue2"`
	}
	Value struct {
		InsideStr string `name:"insideStr"`
	}
)

func main() {
	tryYAML(`---
aValue1.insideStr: "abc"
aValue2:
  insideStr: "def1"
`)

	tryJSON(`{
  "aValue1.insideStr": "abc",
  "aValue2": {
    "insideStr": "def1"
  }
}`)
}

func tryYAML(s string) {
	r, _ := kongyaml.Loader(strings.NewReader(s))
	var cli CLI
	parser, _ := kong.New(&cli, kong.Name("test"), kong.Resolvers(r))
	_, _ = parser.Parse([]string{})
	fmt.Printf("Loaded YAML: %+v\n", cli)
}

func tryJSON(s string) {
	r, _ := kong.JSON(strings.NewReader(s))
	var cli CLI
	parser, _ := kong.New(&cli, kong.Name("test"), kong.Resolvers(r))
	_, _ = parser.Parse([]string{})
	fmt.Printf("Loaded JSON: %+v\n", cli)
}
```

Output:
```
Loaded YAML: {AValue1:{InsideStr:abc} AValue2:{InsideStr:}}
Loaded JSON: {AValue1:{InsideStr:abc} AValue2:{InsideStr:def1}}
```

**Comment by jgillich** [comment]
Had the same issue and it turns out the yaml resolver uses `-` and not `.` for nesting, see https://github.com/alecthomas/kong-yaml/blob/master/yaml_test.go#L21

**Comment by jh125486** [comment]
> Had the same issue and it turns out the yaml resolver uses `-` and not `.` for nesting, see https://github.com/alecthomas/kong-yaml/blob/master/yaml_test.go#L21

Huh.  Still weird that the JSON nesting works. (`InsideStr` is set to `def1` in the example).

**Comment by jgillich** [comment]
Not that weird because the JSON resolver uses `.` :smile:  https://github.com/alecthomas/kong/blob/master/resolver.go#L46 

It's definitely confusing, but I do actually prefer dashes, and you can load JSON with the YAML resolver if you need consistency

**Comment by jh125486** [comment]
Oh, I literally mean the nesting in JSON is being picked up, but not the YAML (the `insideStr` nested inside `aValue2`).

**Comment by jgillich** [comment]
I get that, it's because your prefixes use dots instead of dashes. Change it to
```go
	CLI struct {
		AValue1 Value `prefix:"aValue1-" embed:"" name:"aValue1"`
		AValue2 Value `prefix:"aValue2-" embed:"" name:"aValue2"`
	}
```
and you get
```
Loaded YAML: {AValue1:{InsideStr:} AValue2:{InsideStr:def1}}
Loaded JSON: {AValue1:{InsideStr:} AValue2:{InsideStr:}}
```

**Comment by jh125486** [comment]
Ok, makes way more sense now.

What I'm working on is just such a mix of weird legacy (heritage?) config files and new functionality, this was a big stumbling block.

Thanks!
