### ISSUE TITLE
support parsing nested config structs (cf. kong-hcl)

### ISSUE THREAD

**Issue by costela** [alecthomas/kong-yaml#3]
As discussed in alecthomas/kong#86, it would be great if the YAML loader could support parsing nested config structures.

So something like this:
```yaml
a: true
sub:
  b: true
```
could be parsed into something like this:
```go
type Config struct {
    A bool
    Sub SubConfig
}

type SubConfig struct {
    B bool
}
```

**Comment by alecthomas** [comment]
That should get you started. If you run into any issues, please feel free to send a PR. The code is minimal.

**Comment by costela** [comment]
@alecthomas wow, thanks, that was fast! :sweat_smile:
